sudo: required

services:
- docker

before_install:
- docker pull ibmcom/ibmjava:8-sdk
- docker run -v `pwd`:/work ibmcom/ibmjava:8-sdk /bin/sh -c "javac /work/Main.java"

script:
- docker run -v `pwd`:/work ibmcom/ibmjava:8-sdk /bin/sh -c "java -cp work Main"
